export const PublicEnvs = {
  AUTH0_ISSUER_BASE_URL: process.env.NEXT_PUBLIC_AUTH0_DOMAIN,
  AUTH0_CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID,
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  CALLBACK_URL: process.env.NEXT_PUBLIC_CALLBACK_URL,
  PUBLIC_S3_STORAGE: process.env.NEXT_PUBLIC_S3_STORAGE,
};
